import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import os from 'os';
import { Config } from '../config';
import { MemoryFileManager } from '../memory-file';
import { AcliIntegration } from '../acli-integration';

interface InitOptions {
  sparc?: boolean;
  event?: boolean;
}

export async function initCommand(options: InitOptions): Promise<void> {
  console.log(chalk.green('Initializing rovo-code-flow...'));
  
  if (!options.sparc && !options.event) {
    console.log(chalk.yellow('No modes specified. Initializing with default configuration.'));
    options.sparc = true; // Default to SPARC if no options specified
  }
  
  // Initialize configuration
  const config = new Config();
  
  // Initialize memory files
  const memoryManager = new MemoryFileManager();
  await memoryManager.initMemoryFiles();
  
  // Initialize ACLI integration
  const acli = new AcliIntegration();
  await acli.initRovoDev();
  
  if (options.sparc) {
    console.log(chalk.blue('Initializing SPARC modes...'));
    
    // Update configuration
    config.set('sparc.enabled', true);
    
    // Create SPARC directory structure
    const sparcDir = path.join(process.cwd(), '.sparc');
    if (!fs.existsSync(sparcDir)) {
      fs.mkdirSync(sparcDir, { recursive: true });
    }
    
    // Create mode-specific directories
    const sparcModes = ['architect', 'coder', 'tdd', 'security', 'devops'];
    for (const mode of sparcModes) {
      const modeDir = path.join(sparcDir, mode);
      if (!fs.existsSync(modeDir)) {
        fs.mkdirSync(modeDir, { recursive: true });
      }
    }
    
    // Create SPARC README
    const sparcReadme = path.join(sparcDir, 'README.md');
    if (!fs.existsSync(sparcReadme)) {
      const readmeContent = `# SPARC Modes

This directory contains artifacts generated by SPARC agents.

## Modes

- **architect**: System architecture and design
- **coder**: Implementation and coding
- **tdd**: Test-driven development
- **security**: Security analysis and hardening
- **devops**: Deployment and operations

## Usage

Use the following commands to work with SPARC agents:

\`\`\`bash
# Run SPARC architect agent
rovo-code-flow sparc architect "design authentication system"

# Run SPARC coder agent
rovo-code-flow sparc coder "implement user login"
\`\`\`
`;
      fs.writeFileSync(sparcReadme, readmeContent);
    }
    
    console.log(chalk.green('SPARC modes initialized!'));
  }
  
  if (options.event) {
    console.log(chalk.magenta('Initializing Event Modeling modes...'));
    
    // Update configuration
    config.set('event.enabled', true);
    
    // Create Event Modeling directory structure
    const eventDir = path.join(process.cwd(), '.event-modeling');
    if (!fs.existsSync(eventDir)) {
      fs.mkdirSync(eventDir, { recursive: true });
    }
    
    // Create role-specific directories
    const eventRoles = ['modeler', 'timeline', 'ui', 'state', 'mapper'];
    for (const role of eventRoles) {
      const roleDir = path.join(eventDir, role);
      if (!fs.existsSync(roleDir)) {
        fs.mkdirSync(roleDir, { recursive: true });
      }
    }
    
    // Create Event Modeling README
    const eventReadme = path.join(eventDir, 'README.md');
    if (!fs.existsSync(eventReadme)) {
      const readmeContent = `# Event Modeling Roles

This directory contains artifacts generated by Event Modeling agents.

## Roles

- **modeler**: Core event modeling
- **timeline**: Event timeline planning
- **ui**: UI/UX mapping
- **state**: State modeling
- **mapper**: System mapping

## Usage

Use the following commands to work with Event Modeling agents:

\`\`\`bash
# Run Event Modeling modeler agent
rovo-code-flow event modeler "model password reset flow"

# Run Event Modeling UI mapper agent
rovo-code-flow event ui "map user registration screens"
\`\`\`
`;
      fs.writeFileSync(eventReadme, readmeContent);
    }
    
    console.log(chalk.green('Event Modeling modes initialized!'));
  }
  
  // Initialize repository memory
  console.log(chalk.blue('Initializing repository memory...'));
  await memoryManager.initWithRepoInfo();
  
  console.log(chalk.green('Initialization complete!'));
  
  // Display next steps
  console.log(chalk.blue('\nNext steps:'));
  console.log('1. Run "rovo-code-flow start" to start the orchestrator');
  console.log('2. Run "rovo-code-flow status" to check system health');
  
  if (options.sparc) {
    console.log('3. Run "rovo-code-flow sparc coder <task>" to use the SPARC coder agent');
  }
  
  if (options.event) {
    console.log('3. Run "rovo-code-flow event modeler <task>" to use the Event Modeling modeler agent');
  }
}